/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pelanggan;
import connection.MySQLConnection;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;
import menusewa.SewaForm;
import menusewa.SewaForm;

/**
 *
 * @author RIZKY
 */
public class ListPelanggan extends javax.swing.JFrame {
       Connection CRUDkoneksi;
       String CRUDquery;
       Statement CRUDstat;
       ResultSet CRUDhasil;
    /**
     * Creates new form ListPelanggan
     */
    public ListPelanggan() {
        initComponents();
        try {
            MySQLConnection  Connection = new MySQLConnection();
            CRUDkoneksi = Connection.getKoneksi();
        } catch (Exception ex) {
            System.out.println(ex);
        }
        tampil_data_pelanggan();
    }
    public void tampil_data_pelanggan() {
        Object[] baris = {"id_pelanggan", "nama_pelanggan","no_ktp" ,"alamat","no_hp"};
        DefaultTableModel tabModePelanggan = new DefaultTableModel(null, baris);
        table_pelanggan.setModel(tabModePelanggan);
            CRUDquery = "select * from pelanggan";
        try {
            CRUDstat = CRUDkoneksi.createStatement();
            CRUDhasil = CRUDstat.executeQuery(CRUDquery);
            while (CRUDhasil.next()) {
                tabModePelanggan.addRow(new String[]{CRUDhasil.getString(1),CRUDhasil.getString(2) , CRUDhasil.getString(3),
                CRUDhasil.getString(4),  CRUDhasil.getString(5)} );
            }
        } catch (Exception e) {
            // TODO: handle exception
            System.out.println(e);
        }
    }
    public void autoIdPelanggan(){
        String CRUDquery = "select id_pelanggan from pelanggan ORDER BY id_pelanggan DESC LIMIT 1";
            try {
            Statement CRUDstat = CRUDkoneksi.createStatement();
            ResultSet CRUDhasil = CRUDstat.executeQuery(CRUDquery);
            if(CRUDhasil.next()){
               String a = String.valueOf((CRUDhasil.getInt(1)) + 1);
               SewaForm.txt_id_pelanggan.setText(a);
            }
            }catch (Exception e) {
            System.out.println("Query select Error : " + e);
            }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        table_pelanggan = new javax.swing.JTable();
        btn_pilih = new javax.swing.JButton();
        btn_cancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        table_pelanggan.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        table_pelanggan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "id pelanggan", "nama pelangan", "no ktp", "alamat", "no hp"
            }
        ));
        table_pelanggan.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        table_pelanggan.setRowHeight(20);
        table_pelanggan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_pelangganMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(table_pelanggan);

        btn_pilih.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        btn_pilih.setText("Pilih");
        btn_pilih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pilihActionPerformed(evt);
            }
        });

        btn_cancel.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        btn_cancel.setText("Cancel");
        btn_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 654, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_pilih)
                .addGap(31, 31, 31)
                .addComponent(btn_cancel)
                .addGap(36, 36, 36))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_pilih)
                    .addComponent(btn_cancel))
                .addContainerGap(189, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(696, 713));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void table_pelangganMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_pelangganMouseClicked
        // TODO add your handling code here:
        // TODO add your handling code here:
        try {
            int row = table_pelanggan.rowAtPoint(evt.getPoint());
            String idPelanggan = table_pelanggan.getValueAt(row, 0).toString();
            String namaPelanggan = table_pelanggan.getValueAt(row, 1).toString();
            String noKtp = table_pelanggan.getValueAt(row, 2).toString();
            String alamat = table_pelanggan.getValueAt(row, 3).toString();
            String no_hp = table_pelanggan.getValueAt(row, 4).toString();
            
            SewaForm.txt_id_pelanggan.setText(idPelanggan);
            SewaForm.tf_nama_pelanggan.setText(namaPelanggan);
            SewaForm.tf_no_ktp.setText(noKtp);
            SewaForm.tf_alamat.setText(alamat);
            SewaForm.tf_no_hp.setText(no_hp);
            
            
            
        } catch (Exception e) {
            // TODO: handle exception
        }
    }//GEN-LAST:event_table_pelangganMouseClicked

    private void btn_pilihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pilihActionPerformed
        // TODO add your handling code here:
        
        dispose();
    }//GEN-LAST:event_btn_pilihActionPerformed

    private void btn_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelActionPerformed
        // TODO add your handling code here:
        
        SewaForm.tf_nama_pelanggan.setText("");
        SewaForm.tf_no_ktp.setText("");
        SewaForm.tf_alamat.setText("");
        SewaForm.tf_no_hp.setText("");
        autoIdPelanggan();
        dispose();
    }//GEN-LAST:event_btn_cancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListPelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListPelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListPelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListPelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListPelanggan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cancel;
    private javax.swing.JButton btn_pilih;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable table_pelanggan;
    // End of variables declaration//GEN-END:variables
}
