/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package menuunit;

import connection.MySQLConnection;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import login.FormLogin;
import login.Session;

/**
 *
 * @author RIZKY
 */
public class UnitForm extends javax.swing.JInternalFrame {
    private DefaultTableModel tabmode;
    private ResultSet hasil;
    Unit yo = new Unit();
    Connection CRUDkoneksi;
    Statement st;
    /**
     * Creates new form UnitForm
     */
    public UnitForm() {
        if (Session.getStatusLogin() == "AKTIF") {
            initComponents();
            try {
                MySQLConnection  Connection = new MySQLConnection();
                CRUDkoneksi = Connection.getKoneksi();
            } catch (Exception ex) {
                System.out.println(ex);
            }
            tampil_database();
        }else{
            dispose();
            FormLogin form = new FormLogin();
            form.setVisible(true);
        }
    }
      public void tampil_database() {
        Object[] baris = {"id_mobil", "nama_mobil", "tipe_mobil","no_polisi","harga","keterangan"};
        tabmode = new DefaultTableModel(null, baris);
        table_unit.setModel(tabmode);
        try {
            hasil = yo.tampilData();
            while (hasil.next()) {
                yo.setIdMobil(hasil.getString("id_mobil"));
                yo.setNamaMobil(hasil.getString("nama_mobil"));
                yo.setTipeMobil(hasil.getString("tipe_mobil"));
                yo.setNoPolisi(hasil.getString("no_polisi"));
                yo.setHarga(hasil.getInt("harga"));
                yo.setKeterangan(hasil.getString("keterangan"));
                String[] data = {yo.getIdMobil(), yo.getNamaMobil(), yo.getTipeMobil(), yo.getNoPolisi(), String.valueOf(yo.getHarga()), yo.getKeterangan()};
                tabmode.addRow(data);
            }
        } catch (Exception e) {
            // TODO: handle exception
        }
    }
    
    public void reset_text() {
        tf_id_mobil.setText("");
        tf_nama_mobil.setText("");
        tf_tipe_mobil.setText("");
        tf_no_polisi.setText("");
        tf_harga.setText("");
     
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        table_unit = new javax.swing.JTable();
        btn_tambah = new javax.swing.JButton();
        tfIdMobilPencarian = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tf_tipe_mobil = new javax.swing.JTextField();
        tf_harga = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btn_update = new javax.swing.JButton();
        btn_reset = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        tf_id_mobil = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        tf_nama_mobil = new javax.swing.JTextField();
        tf_no_polisi = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        cbo_keterangan = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1200, 1000));

        table_unit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        table_unit.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        table_unit.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "id mobil", "nama mobil", "tipe mobil", "no_polisi ", "harga perhari", "keterangan"
            }
        ));
        table_unit.setEnabled(false);
        table_unit.setFocusable(false);
        table_unit.setIntercellSpacing(new java.awt.Dimension(3, 3));
        table_unit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_unitMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_unit);

        btn_tambah.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btn_tambah.setText("TAMBAH");
        btn_tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tambahActionPerformed(evt);
            }
        });

        tfIdMobilPencarian.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        tfIdMobilPencarian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfIdMobilPencarianActionPerformed(evt);
            }
        });
        tfIdMobilPencarian.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfIdMobilPencarianKeyReleased(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel4.setText("Tipe Mobil");

        tf_tipe_mobil.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        tf_harga.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        tf_harga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_hargaActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel5.setText("Harga");

        jLabel6.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel6.setText("Keterangan");

        btn_update.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btn_update.setText("Update");
        btn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateActionPerformed(evt);
            }
        });

        btn_reset.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btn_reset.setText("Reset");
        btn_reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_resetActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel8.setText("Id Mobil");

        tf_id_mobil.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel9.setText("Nama Mobil");

        tf_nama_mobil.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        tf_no_polisi.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        jLabel11.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel11.setText("No Polisi");

        cbo_keterangan.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        cbo_keterangan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tersedia", "Tidak Tersedia" }));

        jPanel1.setBackground(new java.awt.Color(204, 255, 0));

        jLabel10.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/car-insurance.png"))); // NOI18N
        jLabel10.setText("Kelola Unit");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(483, 483, 483)
                .addComponent(jLabel10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(387, 387, 387)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_tambah)
                        .addGap(0, 690, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel11)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(tf_tipe_mobil, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel6)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel9))
                                    .addGap(25, 25, 25)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(tf_no_polisi, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(tf_harga, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(tf_nama_mobil, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(tf_id_mobil, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(cbo_keterangan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                    .addComponent(btn_update)
                                                    .addGap(10, 10, 10)))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(btn_reset))))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(420, 420, 420)
                        .addComponent(tfIdMobilPencarian, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tfIdMobilPencarian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(tf_id_mobil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(tf_nama_mobil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(86, 86, 86)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(tf_no_polisi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(tf_harga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(cbo_keterangan, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE))
                            .addComponent(jLabel6)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(tf_tipe_mobil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_tambah)
                    .addComponent(btn_update)
                    .addComponent(btn_reset))
                .addContainerGap(210, Short.MAX_VALUE))
        );

        setBounds(0, 0, 1200, 1000);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tambahActionPerformed
        // TODO add your handling code here:
        if (tf_id_mobil.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Maaf, id mobil belum diisi!");
            tf_id_mobil.requestFocus();
        }else if (tf_nama_mobil.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Maaf, nama mobil belum diisi!");
            tf_nama_mobil.requestFocus();   
        }else if (tf_tipe_mobil.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Maaf, tipe mobil belum diisi!");
            tf_nama_mobil.requestFocus();   
        }else if (tf_no_polisi.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Maaf, no polisi belum diisi!");
            tf_no_polisi.requestFocus();   
        }else if (tf_harga.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Maaf, harga belum diisi!");
            tf_harga.requestFocus();   
        }else{
            try {
                yo.setIdMobil(tf_id_mobil.getText());
                yo.setNamaMobil(tf_nama_mobil.getText());
                yo.setTipeMobil(tf_tipe_mobil.getText());
                yo.setNoPolisi(tf_no_polisi.getText());
                yo.setHarga(Integer.valueOf(tf_harga.getText()));
                yo.setKeterangan(cbo_keterangan.getSelectedItem().toString());
                yo.tambahData(yo.getIdMobil(), yo.getNamaMobil(), yo.getTipeMobil(), yo.getNoPolisi(), yo.getHarga(), yo.getKeterangan());

                JOptionPane.showMessageDialog(null, "Data berhasil tersimpan", "Informasi",
                JOptionPane.INFORMATION_MESSAGE);
                tampil_database();
                reset_text();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Data Gagal Tersimpan", "Informasi", 
                JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }//GEN-LAST:event_btn_tambahActionPerformed

    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateActionPerformed
         if (tf_id_mobil.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Maaf, id mobil belum diisi!");
            tf_id_mobil.requestFocus();
        }else if (tf_nama_mobil.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Maaf, nama mobil belum diisi!");
            tf_nama_mobil.requestFocus();   
        }else if (tf_tipe_mobil.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Maaf, tipe mobil belum diisi!");
            tf_nama_mobil.requestFocus();   
        }else if (tf_no_polisi.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Maaf, no polisi belum diisi!");
            tf_no_polisi.requestFocus();   
        }else if (tf_harga.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Maaf, harga belum diisi!");
            tf_harga.requestFocus();   
        }else{
            try {
                yo.setIdMobil(tf_id_mobil.getText());
                yo.setNamaMobil(tf_nama_mobil.getText());
                yo.setTipeMobil(tf_tipe_mobil.getText());
                yo.setNoPolisi(tf_no_polisi.getText());
                yo.setHarga(Integer.valueOf(tf_harga.getText()));
                yo.setKeterangan(cbo_keterangan.getSelectedItem().toString());
              
                yo.ubahData(yo.getIdMobil(), yo.getNamaMobil(), yo.getTipeMobil(), yo.getNoPolisi(), yo.getHarga(), yo.getKeterangan());

                JOptionPane.showMessageDialog(null, "Data berhasil diubah", "Informasi",
                JOptionPane.INFORMATION_MESSAGE);
                tampil_database();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Data gagal diubah", "Informasi",
                JOptionPane.INFORMATION_MESSAGE);
                
            }
        }
    }//GEN-LAST:event_btn_updateActionPerformed

    private void btn_resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_resetActionPerformed
        // TODO add your handling code here:
        reset_text();
    }//GEN-LAST:event_btn_resetActionPerformed

    private void tf_hargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_hargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_hargaActionPerformed

    private void table_unitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_unitMouseClicked
          try {
            int row = table_unit.rowAtPoint(evt.getPoint());
            
            String id_mobil = table_unit.getValueAt(row, 0).toString();
            String nama_mobil = table_unit.getValueAt(row, 1).toString();
            String tipe_mobil = table_unit.getValueAt(row, 2).toString();
            String no_polisi = table_unit.getValueAt(row, 3).toString();
            String harga = table_unit.getValueAt(row, 4).toString();
            String keterangan = table_unit.getValueAt(row, 5).toString();

            tf_id_mobil.setText(String.valueOf(id_mobil));
            tf_nama_mobil.setText(String.valueOf(nama_mobil));
            tf_tipe_mobil.setText(String.valueOf(tipe_mobil));
            tf_no_polisi.setText(String.valueOf(no_polisi));
            tf_harga.setText(String.valueOf(harga));
        } catch (Exception e) {
            // TODO: handle exception
        }
    }//GEN-LAST:event_table_unitMouseClicked

    private void tfIdMobilPencarianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfIdMobilPencarianActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfIdMobilPencarianActionPerformed

    private void tfIdMobilPencarianKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfIdMobilPencarianKeyReleased
        // TODO add your handling code here:
         try{
            st = CRUDkoneksi.createStatement();
            tabmode.getDataVector().removeAllElements();
            tabmode.fireTableDataChanged();
            ResultSet rs = st.executeQuery("SELECT * FROM unit WHERE id_mobil like '%" + tfIdMobilPencarian.getText() + "%' or nama_mobil like '%" + tfIdMobilPencarian.getText() + "%' or tipe_mobil like '%" + tfIdMobilPencarian.getText() + "%' or no_polisi like '%" + tfIdMobilPencarian.getText() + "%' " + "or harga like '%" + tfIdMobilPencarian.getText() + "%' or keterangan like '%" + tfIdMobilPencarian.getText() + "%'");
            while(rs.next()){
                Object[] data = {
                    rs.getString(1),
                    rs.getString(2),
                    rs.getString(3),
                    rs.getString(4),
                    rs.getString(5),
                    rs.getString(6)
                };
                tabmode.addRow(data);
            }
        }catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_tfIdMobilPencarianKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_reset;
    private javax.swing.JButton btn_tambah;
    private javax.swing.JButton btn_update;
    private javax.swing.JComboBox<String> cbo_keterangan;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table_unit;
    private javax.swing.JTextField tfIdMobilPencarian;
    private javax.swing.JTextField tf_harga;
    private javax.swing.JTextField tf_id_mobil;
    private javax.swing.JTextField tf_nama_mobil;
    private javax.swing.JTextField tf_no_polisi;
    private javax.swing.JTextField tf_tipe_mobil;
    // End of variables declaration//GEN-END:variables
}
